import turtle
import math

#------------------------------
#COORDS:
#print(-50,-round(100 * (1 + math.sqrt(2)) / 2))
#print(-18,-round(36 * (1 + math.sqrt(2)) / 2))
#print(-8,-round(16 * (1 + math.sqrt(2)) / 2))
#print(-50,round(100 * (1 + math.sqrt(2))) + 2 - round(100 * (1 + math.sqrt(2)) / 2))
#print(-32,round(100 * (1 + math.sqrt(2))) + 2 - round(64 * (1 + math.sqrt(2)) / 2))
#print(-18,round(100 * (1 + math.sqrt(2))) + 2 - round(36 * (1 + math.sqrt(2)) / 2))
#print(-8,round(100 * (1 + math.sqrt(2))) + 2 - round(16 * (1 + math.sqrt(2)) / 2))
#print(-50,-1 * (round(100 * (1 + math.sqrt(2))) + 2) - round(100 * (1 + math.sqrt(2)) / 2))
#print(-32,-1 * (round(100 * (1 + math.sqrt(2))) + 2) - round(64 * (1 + math.sqrt(2)) / 2))
#------------------------------


win = turtle.Screen()
win.bgcolor("darkorange")

turtleA = turtle.Turtle()

turtleA.color("navy")
turtleA.speed(0)

turtleA.up()
turtleA.goto(-50,-round(100 * (1 + math.sqrt(2)) / 2))
turtleA.down()

turtleA.begin_fill()
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.end_fill()

turtleA.hideturtle()



turtleB = turtle.Turtle()

turtleB.color("darkorange")
turtleB.speed(0)

turtleB.up()
turtleB.goto(-32,-round(64 * (1 + math.sqrt(2)) / 2))
turtleB.down()

turtleB.begin_fill()
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.end_fill()

turtleB.hideturtle()


turtleC = turtle.Turtle()


turtleC.color("navy")
turtleC.speed(0)

turtleC.up()
turtleC.goto(-18,-round(36 * (1 + math.sqrt(2)) / 2))
turtleC.down()

turtleC.begin_fill()
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.end_fill()

turtleC.hideturtle()


turtleD = turtle.Turtle()

turtleD.color("darkorange")
turtleD.speed(0)

turtleD.up()
turtleD.goto(-8,-round(16 * (1 + math.sqrt(2)) / 2))
turtleD.down()

turtleD.begin_fill()
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.end_fill()

turtleD.hideturtle()


turtleE = turtle.Turtle()
turtleE.color("navy")
turtleE.speed(0)
turtleE.shape("turtle")
turtleE.up()
turtleE.goto(-2,0)
turtleE.down()
turtleE.stamp()

turtleA.up()
turtleA.goto(-50,round(100 * (1 + math.sqrt(2))) + 2 - round(100 * (1 + math.sqrt(2)) / 2))
turtleA.down()
turtleA.showturtle()

turtleA.begin_fill()
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.end_fill()

turtleA.hideturtle()

turtleB.up()
turtleB.goto(-32,round(100 * (1 + math.sqrt(2))) + 2 - round(64 * (1 + math.sqrt(2)) / 2))
turtleB.down()
turtleB.showturtle()

turtleB.begin_fill()
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.end_fill()

turtleB.hideturtle()

turtleC.up()
turtleC.goto(-18,round(100 * (1 + math.sqrt(2))) + 2 - round(36 * (1 + math.sqrt(2)) / 2))
turtleC.down()
turtleC.showturtle()

turtleC.begin_fill()
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.end_fill()

turtleC.hideturtle()

turtleD.up()
turtleD.goto(-8,round(100 * (1 + math.sqrt(2))) + 2 - round(16 * (1 + math.sqrt(2)) / 2))
turtleD.down()
turtleD.showturtle()

turtleD.begin_fill()
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.end_fill()

turtleD.hideturtle()

turtleE.up()
turtleE.goto(-2,round(100 * (1 + math.sqrt(2))) + 2)
turtleE.down()
turtleE.stamp()


turtleA.up()
turtleA.goto(-50,-1 * (round(100 * (1 + math.sqrt(2))) + 2) - round(100 * (1 + math.sqrt(2)) / 2))
turtleA.down()
turtleA.showturtle()

turtleA.begin_fill()
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.end_fill()

turtleA.hideturtle()

turtleB.up()
turtleB.goto(-32,-1 * (round(100 * (1 + math.sqrt(2))) + 2) - round(64 * (1 + math.sqrt(2)) / 2))
turtleB.down()
turtleB.showturtle()

turtleB.begin_fill()
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.end_fill()

turtleB.hideturtle()

turtleC.up()
turtleC.goto(-18,-1 * (round(100 * (1 + math.sqrt(2))) + 2) - round(36 * (1 + math.sqrt(2)) / 2))
turtleC.down()
turtleC.showturtle()

turtleC.begin_fill()
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.end_fill()

turtleC.hideturtle()

turtleD.up()
turtleD.goto(-8,-1 * (round(100 * (1 + math.sqrt(2))) + 2) - round(16 * (1 + math.sqrt(2)) / 2))
turtleD.down()
turtleD.showturtle()

turtleD.begin_fill()
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.end_fill()

turtleD.hideturtle()


turtleE.up()
turtleE.goto(-2,-1 * (round(100 * (1 + math.sqrt(2))) + 2))
turtleE.down()
turtleE.stamp()


turtleA.up()
turtleA.goto(round(100 * (1 + math.sqrt(2))) + 4 - 50,round(100 * (1 + math.sqrt(2))) + 2 - round(100 * (1 + math.sqrt(2)) / 2))
turtleA.down()
turtleA.showturtle()

turtleA.begin_fill()
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.end_fill()

turtleA.hideturtle()

turtleB.up()
turtleB.goto(round(100 * (1 + math.sqrt(2))) + 4 - 32,round(100 * (1 + math.sqrt(2))) + 2 - round(64 * (1 + math.sqrt(2)) / 2))
turtleB.down()
turtleB.showturtle()

turtleB.begin_fill()
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.end_fill()

turtleB.hideturtle()

turtleC.up()
turtleC.goto(round(100 * (1 + math.sqrt(2))) + 4 - 18,round(100 * (1 + math.sqrt(2))) + 2 - round(36 * (1 + math.sqrt(2)) / 2))
turtleC.down()
turtleC.showturtle()

turtleC.begin_fill()
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.end_fill()

turtleC.hideturtle()

turtleD.up()
turtleD.goto(round(100 * (1 + math.sqrt(2))) + 4 - 8,round(100 * (1 + math.sqrt(2))) + 2 - round(16 * (1 + math.sqrt(2)) / 2))
turtleD.down()
turtleD.showturtle()

turtleD.begin_fill()
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.end_fill()

turtleD.hideturtle()


turtleE.up()
turtleE.goto(round(100 * (1 + math.sqrt(2))) + 4 - 2,round(100 * (1 + math.sqrt(2))) + 2)
turtleE.down()
turtleE.stamp()


turtleA.up()
turtleA.goto(- round(100 * (1 + math.sqrt(2))) - 4 - 50,round(100 * (1 + math.sqrt(2))) + 2 - round(100 * (1 + math.sqrt(2)) / 2))
turtleA.down()
turtleA.showturtle()

turtleA.begin_fill()
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.end_fill()

turtleA.hideturtle()

turtleB.up()
turtleB.goto(- round(100 * (1 + math.sqrt(2))) - 4 - 32,round(100 * (1 + math.sqrt(2))) + 2 - round(64 * (1 + math.sqrt(2)) / 2))
turtleB.down()
turtleB.showturtle()

turtleB.begin_fill()
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.end_fill()

turtleB.hideturtle()

turtleC.up()
turtleC.goto(- round(100 * (1 + math.sqrt(2))) - 4 - 18,round(100 * (1 + math.sqrt(2))) + 2 - round(36 * (1 + math.sqrt(2)) / 2))
turtleC.down()
turtleC.showturtle()

turtleC.begin_fill()
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.end_fill()

turtleC.hideturtle()

turtleD.up()
turtleD.goto(- round(100 * (1 + math.sqrt(2))) - 4 - 8,round(100 * (1 + math.sqrt(2))) + 2 - round(16 * (1 + math.sqrt(2)) / 2))
turtleD.down()
turtleD.showturtle()

turtleD.begin_fill()
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.end_fill()

turtleD.hideturtle()


turtleE.up()
turtleE.goto(- round(100 * (1 + math.sqrt(2))) - 4 - 2,round(100 * (1 + math.sqrt(2))) + 2)
turtleE.down()
turtleE.stamp()


turtleA.up()
turtleA.goto(round(100 * (1 + math.sqrt(2))) + 4 - 50,- round(100 * (1 + math.sqrt(2)) / 2))
turtleA.down()
turtleA.showturtle()

turtleA.begin_fill()
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.end_fill()

turtleA.hideturtle()

turtleB.up()
turtleB.goto(round(100 * (1 + math.sqrt(2))) + 4 - 32,- round(64 * (1 + math.sqrt(2)) / 2))
turtleB.down()
turtleB.showturtle()

turtleB.begin_fill()
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.end_fill()

turtleB.hideturtle()

turtleC.up()
turtleC.goto(round(100 * (1 + math.sqrt(2))) + 4 - 18, - round(36 * (1 + math.sqrt(2)) / 2))
turtleC.down()
turtleC.showturtle()

turtleC.begin_fill()
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.end_fill()

turtleC.hideturtle()

turtleD.up()
turtleD.goto(round(100 * (1 + math.sqrt(2))) + 4 - 8, - round(16 * (1 + math.sqrt(2)) / 2))
turtleD.down()
turtleD.showturtle()

turtleD.begin_fill()
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.end_fill()

turtleD.hideturtle()


turtleE.up()
turtleE.goto(round(100 * (1 + math.sqrt(2))) + 4 - 2,0)
turtleE.down()
turtleE.stamp()


turtleA.up()
turtleA.goto(- round(100 * (1 + math.sqrt(2))) - 4 - 50,- round(100 * (1 + math.sqrt(2)) / 2))
turtleA.down()
turtleA.showturtle()

turtleA.begin_fill()
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.end_fill()

turtleA.hideturtle()

turtleB.up()
turtleB.goto(- round(100 * (1 + math.sqrt(2))) - 4 - 32,- round(64 * (1 + math.sqrt(2)) / 2))
turtleB.down()
turtleB.showturtle()

turtleB.begin_fill()
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.end_fill()

turtleB.hideturtle()

turtleC.up()
turtleC.goto(- round(100 * (1 + math.sqrt(2))) - 4 - 18,- round(36 * (1 + math.sqrt(2)) / 2))
turtleC.down()
turtleC.showturtle()

turtleC.begin_fill()
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.end_fill()

turtleC.hideturtle()

turtleD.up()
turtleD.goto(- round(100 * (1 + math.sqrt(2))) - 4 - 8,- round(16 * (1 + math.sqrt(2)) / 2))
turtleD.down()
turtleD.showturtle()

turtleD.begin_fill()
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.end_fill()

turtleD.hideturtle()


turtleE.up()
turtleE.goto(- round(100 * (1 + math.sqrt(2))) - 4 - 2,0)
turtleE.down()
turtleE.stamp()


turtleA.up()
turtleA.goto(round(100 * (1 + math.sqrt(2))) + 4 - 50,-1 * (round(100 * (1 + math.sqrt(2))) + 2) - round(100 * (1 + math.sqrt(2)) / 2))
turtleA.down()
turtleA.showturtle()

turtleA.begin_fill()
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.end_fill()

turtleA.hideturtle()

turtleB.up()
turtleB.goto(round(100 * (1 + math.sqrt(2))) + 4 - 32,-1 * (round(100 * (1 + math.sqrt(2))) + 2) - round(64 * (1 + math.sqrt(2)) / 2))
turtleB.down()
turtleB.showturtle()

turtleB.begin_fill()
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.end_fill()

turtleB.hideturtle()

turtleC.up()
turtleC.goto(round(100 * (1 + math.sqrt(2))) + 4 - 18,-1 * (round(100 * (1 + math.sqrt(2))) + 2) - round(36 * (1 + math.sqrt(2)) / 2))
turtleC.down()
turtleC.showturtle()

turtleC.begin_fill()
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.end_fill()

turtleC.hideturtle()

turtleD.up()
turtleD.goto(round(100 * (1 + math.sqrt(2))) + 4 - 8,-1 * (round(100 * (1 + math.sqrt(2))) + 2) - round(16 * (1 + math.sqrt(2)) / 2))
turtleD.down()
turtleD.showturtle()

turtleD.begin_fill()
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.end_fill()

turtleD.hideturtle()


turtleE.up()
turtleE.goto(round(100 * (1 + math.sqrt(2))) + 4 - 2,-1 * (round(100 * (1 + math.sqrt(2))) + 2))
turtleE.down()
turtleE.stamp()


turtleA.up()
turtleA.goto(- round(100 * (1 + math.sqrt(2))) - 4 - 50,-1 * (round(100 * (1 + math.sqrt(2))) + 2) - round(100 * (1 + math.sqrt(2)) / 2))
turtleA.down()
turtleA.showturtle()

turtleA.begin_fill()
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.forward(100)
turtleA.left(45)
turtleA.end_fill()

turtleA.hideturtle()

turtleB.up()
turtleB.goto(- round(100 * (1 + math.sqrt(2))) - 4 - 32,-1 * (round(100 * (1 + math.sqrt(2))) + 2) - round(64 * (1 + math.sqrt(2)) / 2))
turtleB.down()
turtleB.showturtle()

turtleB.begin_fill()
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.forward(64)
turtleB.left(45)
turtleB.end_fill()

turtleB.hideturtle()

turtleC.up()
turtleC.goto(- round(100 * (1 + math.sqrt(2))) - 4 - 18,-1 * (round(100 * (1 + math.sqrt(2))) + 2) - round(36 * (1 + math.sqrt(2)) / 2))
turtleC.down()
turtleC.showturtle()

turtleC.begin_fill()
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.forward(36)
turtleC.left(45)
turtleC.end_fill()

turtleC.hideturtle()

turtleD.up()
turtleD.goto(- round(100 * (1 + math.sqrt(2))) - 4 - 8,-1 * (round(100 * (1 + math.sqrt(2))) + 2) - round(16 * (1 + math.sqrt(2)) / 2))
turtleD.down()
turtleD.showturtle()

turtleD.begin_fill()
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.forward(16)
turtleD.left(45)
turtleD.end_fill()

turtleD.hideturtle()


turtleE.up()
turtleE.goto(- round(100 * (1 + math.sqrt(2))) - 4 - 2,-1 * (round(100 * (1 + math.sqrt(2))) + 2))
turtleE.down()
turtleE.stamp()


win.exitonclick()